//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE
    {
        public System.Guid CANDIDATE_ID { get; set; }
        public string CANDIDATE_NAME { get; set; }
        public System.Guid JOB_ID { get; set; }
        public decimal YEARS_OF_EXP_TOTAL { get; set; }
        public Nullable<int> YEARS_OF_EXP_RELEVANT { get; set; }
        public string MOBILE_NO { get; set; }
        public string ALTERNATE_MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string ALTERNATE_EMAIL_ID { get; set; }
        public System.DateTime DOB { get; set; }
        public string CURRENT_COMPANY { get; set; }
        public string CURRENT_LOCATION { get; set; }
        public string NOTICE_PERIOD { get; set; }
        public Nullable<bool> ANY_OTHER_OFFER { get; set; }
        public Nullable<System.DateTime> LAST_WORKING_DATE { get; set; }
        public string COMMENTS { get; set; }
        public string RESUME_FILE_PATH { get; set; }
        public string RESUME_SOURCE { get; set; }
        public Nullable<bool> ISINNOTICEPERIOD { get; set; }
        public string STATUS { get; set; }
        public bool ISACTIVE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    
        public virtual JOBPOSTING JOBPOSTING { get; set; }
    }
}
