//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_LOG
    {
        public System.Guid ERR_ID { get; set; }
        public string ERR_TYPE { get; set; }
        public string ERR_DESC { get; set; }
        public string ERR_CODE { get; set; }
        public string ERR_SYSTEM_ID { get; set; }
        public string ERR_SYSTEM_NAME { get; set; }
        public string ERR_PAGE { get; set; }
        public string ERR_EVENT { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
    }
}
