//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOBPOSTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JOBPOSTING()
        {
            this.CANDIDATES = new HashSet<CANDIDATE>();
            this.JOB_HISTORY = new HashSet<JOB_HISTORY>();
        }
    
        public System.Guid JOB_ID { get; set; }
        public string JOB_CODE { get; set; }
        public string JOB_DESCRIPTION { get; set; }
        public string POSITION_NAME { get; set; }
        public int NO_OF_VACANCIES { get; set; }
        public string YEARS_OF_EXP_TOTAL { get; set; }
        public string YEARS_OF_EXP_RELEVANT { get; set; }
        public string WORK_LOCATION { get; set; }
        public string COMMENTS { get; set; }
        public string JD_FILE_PATH { get; set; }
        public string JD_SOURCE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string STATUS { get; set; }
        public bool ISACTIVE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string POSITION_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATE> CANDIDATES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOB_HISTORY> JOB_HISTORY { get; set; }
    }
}
