//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_MASTER_HISTORY
    {
        public System.Guid STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string STATUS_DESCRIPTION { get; set; }
        public Nullable<System.Guid> JOB_ID { get; set; }
        public bool ISACTIVE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    }
}
