//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_MASTER
    {
        public System.Guid VENDOR_ID { get; set; }
        public string VENDOR_NAME { get; set; }
        public string VENDOR_SPOC { get; set; }
        public string EMAIL { get; set; }
        public string VENDOR_CONTACT_NO { get; set; }
        public bool ISACTIVE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string VENDOR_TYPE { get; set; }
    
        public virtual JOBXVENDOR JOBXVENDOR { get; set; }
    }
}
